export const CURRENCY = "usd";
export const YEARLY_DISCOUNT = 0.8;
export const MONTHLY_PRICES = {
  MONTHLY_PREMIUM: 10.0,
};
export const MONTHLY_PRICING = {
  ...MONTHLY_PRICES,
  YEARLY_PREMIUM: MONTHLY_PRICES["MONTHLY_PREMIUM"] * YEARLY_DISCOUNT,
};
export const SUBSCRIPTION_IDS = {
  STRIPE_YEARLY_UNLIMITED_SUB_ID: process.env.STRIPE_YEARLY_PREMIUM_SUB_ID,
  STRIPE_MONTHLY_MULTI_SUB_ID: process.env.STRIPE_MONTHLY_PREMIUM_SUB_ID,
  STRIPE_MONTHLY_SINGLE_SUB_ID: process.env.STRIPE_STANDARD_FREE_SUB_ID,
};

export const TRIAL_PERIOD_DAYS = 14;
